version: '2'
services:
  rest-gpio:
    image: homesensor/gpio
    container_name: homesensor-gpio
    privileged: true
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/mem:/dev/mem"
    ports: 
      - "3001:3000"
    volumes:
      - ~/Documents/Home-Sensor/config/gpio_config.json:/usr/src/app/config.json
